#!/usr/bin/env python
#
# Copyright (C) 2009,2010 Junta de Andalucia
# 
# Authors:
#   Roberto Majadas <roberto.majadas at openshine.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
# USA

import os
import sys
if os.name == "posix" :
    import syslog
import gtk 
import gettext
import __builtin__

if os.name == "nt" :
    if not hasattr(sys, "frozen") :
        sys.stdout = open(os.devnull, 'w')
        sys.stderr = open(os.devnull, 'w')
        root_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        nanny_lib_path = os.path.join(root_path, "lib", "python2.6", "site-packages")
        sys.path.append(nanny_lib_path)

import nanny.client.gnome.admin

if __name__ == '__main__':
    __builtin__._ = gettext.gettext

    desktop_blocker = nanny.client.gnome.admin.DesktopBlocker()
    desktop_blocker.show()
    gtk.gdk.keyboard_grab(desktop_blocker.window)
    gtk.main()
    sys.exit(0)

