#!/bin/sh
### BEGIN INIT INFO
# Provides:          nanny-daemon
# Required-Start:    boot.localnet dbus 
# Should-Start:      
# Required-Stop:     
# Should-Stop:
# Default-Start:     3 5
# Default-Stop:      
# Short-Description: nanny-daemon is a daemon to management the nanny's parental control
# Description:       nanny-daemon is a daemon to management the nanny's parental control
#                    
### END INIT INFO